### PR TITLE
add proxy paramater in PveClient

### PR DESCRIPTION
**Pull request by alone-wolf**

### CODE REVIEW

**Comment by franklupo** [comment]
Hi,
Nice idea, but the Proxy would be better if it were a property get/set and not a constructor parameter.

Best reagrds

**Comment by alone-wolf** [comment]
but I think the proxy property should be a final one or immutable one, due to the security reasons

**Comment by franklupo** [comment]
Change only in PveClientBase.java add property in this file, like a *ResponseType* set/get

best regards

**Comment by alone-wolf** [comment]
> Change only in PveClientBase.java add property in this file, like a *ResponseType* set/get
> 
> best regards

Sorry for not providing progress for a long time. I have been working on my job for a while. I will rewrite the code and resubmit in the near future. Thank you to the code repository owner for waiting.

**Comment by alone-wolf** [comment]
> Change only in PveClientBase.java add property in this file, like a *ResponseType* set/get
> 
> best regards

Sorry for not providing progress for a long time. I have been working on my job for a while. I will rewrite the code and resubmit in the near future. Thank you to the code repository owner for waiting.

**Comment by franklupo** [comment]
I fix in next release

**Pull request closed without merging**
